network:
  version: 2
  ethernets:
    ens5:
      dhcp4-overrides:
        use-dns: false
      dhcp6-overrides:
        use-dns: false
      nameservers:
        addresses:
          - 172.26.0.2
          - 1.1.1.1
          - 8.8.8.8
        search:
          - ap-northeast-2.compute.internal
